"""C#: one file per building, namespace scope, project configs and symbol resolution.

tree-sitter-csharp does not parse preprocessor directives (#if/#endif) or some
newer syntax inside them; parse errors from those gaps are suppressed so FIRE
stays on for genuine syntax mistakes.
"""

import fnmatch
import os
import re
import xml.etree.ElementTree as ET

import langkit

NAME = "csharp"
LABEL = "C#"
EXTENSIONS = (".cs",)
SHEBANGS = ()
GRAMMARS = {".cs": "csharp"}
CONFIG = ("*.csproj", "Directory.Packages.props", "Directory.Build.props")
FIRE = True
SAMPLE = {
    "src/Core/Core.csproj": (
        '<Project Sdk="Microsoft.NET.Sdk"><PropertyGroup><RootNamespace>Acme.Core</RootNamespace>'
        "</PropertyGroup></Project>\n"
    ),
    "src/Core/Parser.cs": "namespace Acme.Core;\n\npublic class Parser {}\n",
    "src/App/App.csproj": (
        '<Project Sdk="Microsoft.NET.Sdk"><ItemGroup>'
        '<ProjectReference Include="..\\Core\\Core.csproj" />'
        "</ItemGroup></Project>\n"
    ),
    "src/App/Program.cs": (
        "using Acme.Core;\n\nnamespace Acme.App;\n\npublic class Program {\n"
        "  void Run() { var p = new Parser(); }\n}\n"
    ),
}

GRAMMAR = "csharp"
COMMENT = {"comment"}
TYPE_NODES = frozenset({
    "class_declaration", "struct_declaration", "interface_declaration",
    "enum_declaration", "record_declaration", "delegate_declaration",
})
MEMBER_NODES = frozenset({
    "method_declaration", "property_declaration", "field_declaration",
    "event_declaration", "constructor_declaration", "indexer_declaration",
})
COMPLEXITY = (
    "if_statement", "for_statement", "foreach_statement", "while_statement",
    "do_statement", "switch_section", "switch_expression_arm", "catch_clause",
    "conditional_expression", ("binary_expression", ("&&", "||", "??")),
)
FUNCTIONS = ("method_declaration", "constructor_declaration", "destructor_declaration",
             "operator_declaration", "conversion_operator_declaration", "local_function_statement")
FRAMEWORK = frozenset({"System", "Microsoft.CSharp", "Microsoft.VisualBasic", "Microsoft.Win32"})
TEST_PACKAGES = ("xunit", "nunit", "mstest", "microsoft.net.test.sdk")
GENERATED_NAMES = frozenset({"GlobalUsings.g.cs", "AssemblyInfo.cs"})
GENERATED_SUFFIXES = (".g.cs", ".g.i.cs", ".Designer.cs")
PUBLIC_TYPE = re.compile(
    r"^\s*public\s+(?:(?:partial|static|unsafe|new|abstract|sealed)\s+)*"
    r"(?:class|struct|interface|enum|record|delegate)\s+(\w+)",
    re.MULTILINE,
)
RESERVED = frozenset({
    "var", "void", "int", "string", "bool", "object", "byte", "short", "long",
    "float", "double", "decimal", "char", "uint", "ulong", "ushort", "sbyte",
    "true", "false", "null", "new", "this", "base",
})

# scan() fills this; resolver() reads it. Cleared at the start of each resolver() call.
_partial_by_file = {}


def unit_of(path, files):
    return path


def is_test(path, text=None):
    name = os.path.basename(path)
    if name.endswith("Tests.cs") or name.endswith("Test.cs"):
        return True
    if any(p.endswith(".Tests") or p in ("Tests", "Test") for p in path.split("/")):
        return True
    if text:
        for needle in ("using Xunit", "using NUnit", "using Microsoft.VisualStudio.TestTools",
                       "[Fact]", "[Theory]", "[Test]", "[TestMethod]"):
            if needle in text:
                return True
    return False


def is_excluded(path, text):
    parts = path.split("/")
    if "obj" in parts or "bin" in parts:
        return True
    base = os.path.basename(path)
    if base in GENERATED_NAMES or any(base.endswith(s) for s in GENERATED_SUFFIXES):
        return True
    if text and text.lstrip().startswith("/*") and "<auto-generated" in text[:500].lower():
        return True
    return False


def scan(path, text, tree):
    if tree is None:
        return langkit.Facts()
    try:
        declares, exports, scopes, usings, partials = _file_facts(tree)
        scope = scopes[0] if len(scopes) == 1 else ""
        _supplement_public_types(text, declares, exports, scope, partials)
        _partial_by_file[path] = partials
        references = _references(tree)
        imports = _import_objects(usings) + tuple(
            langkit.Import(n, names=(s,), kind="reference") for s, n in references)
        scope = scopes[0] if len(scopes) == 1 else None
        return langkit.Facts(
            loc=langkit.loc(text, tree, COMMENT),
            complexity=_complexity(tree.root_node),
            exports=tuple(exports),
            notes=langkit.notes(tree, COMMENT),
            is_entry=_is_entry(tree),
            parse_error=_parse_error(tree, text),
            imports=imports,
            scope=scope,
            declares=tuple((s, n) for s, n, _ in declares),
            references=tuple(n for _, n in references),
            functions=langkit.functions(tree.root_node, FUNCTIONS, _complexity),
        )
    except Exception:
        return langkit.Facts(parse_error=_parse_error(tree, text))


def test_files(configs, files):
    projects = _projects(configs)
    test_projs = {p for p, proj in projects.items() if p and proj.is_test}
    return {f for f in files if f.endswith(".cs") and _file_project(f, projects) in test_projs}


def enrich(facts, configs, files):
    projects = _projects(configs)
    for path, fx in facts.items():
        proj = projects.get(_file_project(path, projects), projects[""])
        if proj.is_test or proj.output_type in ("Exe", "WinExe"):
            continue
        if _has_public_top_level(fx):
            fx.public = True


def resolver(facts, configs, files):
    stale = [p for p in _partial_by_file if p not in facts]
    for p in stale:
        del _partial_by_file[p]
    projects = _projects(configs)
    proj_of = {p: _file_project(p, projects) for p in facts}
    by_file = {}
    for path, fx in facts.items():
        proj_key = proj_of[path]
        proj = projects.get(proj_key, projects[""])
        by_file[path] = fx
    index = langkit.SymbolIndex((scope, name, p) for p, fx in facts.items()
                                for scope, name in fx.declares)
    global_by_project = {}
    for path, fx in facts.items():
        key = proj_of[path]
        global_by_project.setdefault(key, set()).update(
            _strip_global(u.spec) for u in fx.imports if u.kind == "global")
    for path in facts:
        proj_key = proj_of[path]
        projects.setdefault(proj_key, projects[""]).global_usings |= global_by_project.get(
            proj_key, set())
    return _Resolver(by_file, proj_of, projects, index)


class _Project:
    __slots__ = ("path", "packages", "global_usings", "is_test", "root_namespace",
                 "output_type")

    def __init__(self, path, packages, global_usings, is_test, root_namespace, output_type):
        self.path = path
        self.packages = packages
        self.global_usings = global_usings
        self.is_test = is_test
        self.root_namespace = root_namespace
        self.output_type = output_type


class _Resolver:
    def __init__(self, by_file, proj_of, projects, index):
        self._by_file = by_file
        self._proj_of = proj_of
        self._projects = projects
        self._index = index

    def resolve(self, path, imp):
        if imp.kind == "reference":
            ref_scope = imp.names[0] if imp.names else None
            return self._reference(path, imp.spec, ref_scope), None
        spec = _strip_global(imp.spec)
        if imp.kind == "global":
            return frozenset(), None
        if _is_framework(spec):
            return frozenset(), None
        if _using_names_type(spec):
            hit = self._type_target(spec)
            if hit:
                return frozenset({hit}), None
        if self._index.in_scope(spec):
            return frozenset(), None
        proj = self._projects.get(self._proj_of[path], self._projects[""])
        return frozenset(), _warehouse(spec, proj.packages)

    def _reference(self, path, name, ref_scope=None):
        proj = self._projects.get(self._proj_of[path], self._projects[""])
        base = ref_scope if ref_scope is not None else _file_scope(path, self._by_file)
        scopes = _scope_chain(base)
        for trial in (name, name + "Attribute"):
            for scope in scopes:
                hit = self._lookup(scope, trial, path)
                if hit:
                    return hit
            for scope in sorted(proj.global_usings):
                hit = self._lookup(scope, trial, path)
                if hit:
                    return hit
            for scope in _local_usings(path, self._by_file):
                hit = self._lookup(scope, trial, path)
                if hit:
                    return hit
        return frozenset()

    def _lookup(self, scope, name, here):
        paths = self._index.lookup_all(scope, name)
        if not paths:
            return frozenset()
        if len(paths) == 1:
            return frozenset({paths[0]}) if paths[0] != here else frozenset()
        if all(_partial_by_file.get(p, {}).get((scope, name), False) for p in paths):
            return frozenset(p for p in paths if p != here)
        return frozenset()

    def _type_target(self, spec):
        parts = spec.split(".")
        if len(parts) < 2:
            return None
        return self._index.lookup(".".join(parts[:-1]), parts[-1])


def _file_scope(path, by_file):
    fx = by_file.get(path)
    return fx.scope if fx and fx.scope is not None else ""


def _local_usings(path, by_file):
    fx = by_file.get(path)
    if not fx:
        return ()
    return tuple(_strip_global(u.spec) for u in fx.imports if u.kind == "import")


def _import_objects(usings):
    seen, out = set(), []
    for kind, spec in usings:
        if spec not in seen:
            seen.add(spec)
            out.append(langkit.Import(spec, kind=kind))
    return tuple(out)


def _file_facts(tree):
    declares, exports, scopes, usings = [], [], set(), []
    partials = {}
    file_scope = ""

    def walk_decl(node, scope):
        name = _type_name(node)
        if not name:
            return
        is_partial = _has_modifier(node, "partial")
        declares.append((scope, name, is_partial))
        partials[(scope, name)] = is_partial
        if _has_modifier(node, "public"):
            exports.append(name)
            for child in node.children:
                if child.type != "declaration_list":
                    continue
                for member in child.children:
                    if member.type in MEMBER_NODES and _has_modifier(member, "public"):
                        mname = _member_name(member)
                        if mname:
                            exports.append(mname)

    def walk_block(node, scope):
        if node.type in TYPE_NODES:
            walk_decl(node, scope)
            return
        if node.type == "namespace_declaration":
            inner = _qualified(node)
            inner_scope = f"{scope}.{inner}" if scope else inner
            scopes.add(inner_scope)
            for child in node.children:
                if child.type == "declaration_list":
                    for decl in child.children:
                        walk_block(decl, inner_scope)
            return
        for child in node.children:
            walk_block(child, scope)

    for child in tree.root_node.children:
        if child.type == "using_directive":
            usings.extend(_parse_using(child))
        elif child.type == "file_scoped_namespace_declaration":
            file_scope = _qualified(child)
            scopes.add(file_scope)
        elif child.type == "namespace_declaration":
            walk_block(child, "")
        elif child.type in TYPE_NODES:
            walk_decl(child, file_scope)
        elif child.type == "global_statement":
            continue
        else:
            walk_block(child, file_scope)

    return declares, exports, sorted(scopes), usings, partials


def _parse_using(node):
    kind = "global" if any(c.type == "global" for c in node.children) else "import"
    if _using_is_alias(node):
        target = _using_target(node)
        return [(kind, target)] if target else []
    target = _using_target(node)
    return [(kind, target)] if target else []


def _using_is_alias(node):
    for i, child in enumerate(node.children):
        if child.type == "identifier" and i + 1 < len(node.children) and node.children[i + 1].type == "=":
            return True
    return False


def _using_target(node):
    seen_eq = False
    parts = []
    for child in node.children:
        if child.type == "=":
            seen_eq = True
            parts = []
            continue
        if child.type in ("identifier", "qualified_name", "alias_qualified_name"):
            if not seen_eq and child.type == "identifier" and _using_is_alias(node):
                continue
            text = _clean_name(langkit.node_text(child))
            if text:
                parts.append(text)
    if not parts:
        return ""
    if len(parts) == 1:
        return parts[0]
    return ".".join(parts)


def _references(tree):
    refs = {}
    file_scope = ""
    for child in tree.root_node.children:
        if child.type == "file_scoped_namespace_declaration":
            file_scope = _qualified(child)
    for node in langkit.walk(tree.root_node):
        if node.type != "identifier":
            continue
        if not _reference_use(node):
            continue
        name = langkit.node_text(node)
        if not name or name in RESERVED:
            continue
        scope = _namespace_of(node, tree, file_scope)
        refs.setdefault((scope, name), None)
    return tuple(sorted(refs))


def _reference_use(node):
    parent = node.parent
    if parent is None:
        return False
    if parent.type in ("base_list", "object_creation_expression", "attribute"):
        return True
    if parent.type == "member_access_expression" and parent.child(0) == node:
        return True
    if parent.type == "generic_name" and parent.child(0) == node:
        return True
    if parent.type == "qualified_name" and parent.child(0) == node:
        grand = parent.parent
        if grand and grand.type in ("base_list", "variable_declaration", "parameter"):
            return True
    if parent.type in ("variable_declaration", "parameter", "field_declaration"):
        return _first_type(parent) == node
    return False


def _first_type(node):
    for child in node.children:
        if child.type == "variable_declaration":
            return _first_type(child)
        if child.type in ("identifier", "qualified_name", "generic_name", "predefined_type",
                          "nullable_type", "array_type"):
            return child
    return None


def _is_entry(tree):
    for node in langkit.walk(tree.root_node):
        if node.type == "global_statement":
            return True
        if node.type == "method_declaration" and _member_name(node) == "Main":
            if _has_modifier(node, "static"):
                return True
    return False


def _has_modifier(node, word):
    for child in node.children:
        if child.type != "modifier":
            continue
        if any(c.type == word for c in child.children):
            return True
    return False


def _type_name(node):
    for child in node.children:
        if child.type == "identifier":
            return langkit.node_text(child)
    return None


def _member_name(node):
    for child in node.children:
        if child.type == "identifier":
            return langkit.node_text(child)
    return None


def _qualified(node):
    for child in node.children:
        if child.type == "qualified_name":
            return _clean_name(langkit.node_text(child))
        if child.type == "identifier":
            return langkit.node_text(child)
    return ""


def _clean_name(text):
    if text.startswith("global::"):
        return text[8:]
    return text


def _strip_global(spec):
    return spec[8:] if spec.startswith("global::") else spec


def _is_framework(spec):
    return spec in FRAMEWORK or spec == "System" or spec.startswith("System.")


def _using_names_type(spec):
    if "." not in spec:
        return False
    last = spec.rsplit(".", 1)[-1]
    return bool(last) and last[0].isupper()


def _scope_chain(scope):
    parts = scope.split(".") if scope else []
    return [".".join(parts[:i]) for i in range(len(parts), -1, -1)]


def _warehouse(spec, packages):
    best = ""
    for pkg in packages:
        if spec == pkg or spec.startswith(pkg + "."):
            if len(pkg) > len(best):
                best = pkg
    if best:
        return best
    parts = spec.split(".")
    return ".".join(parts[:2]) if len(parts) >= 2 else spec


def _tag(tag):
    return tag.split("}", 1)[-1]


def _projects(configs):
    central, shared = set(), set()
    for path, text in configs.items():
        base = os.path.basename(path)
        if base == "Directory.Packages.props":
            central.update(_package_refs(text))
        elif base == "Directory.Build.props":
            shared.update(_package_refs(text))
    extra = central | shared
    projects = {"": _Project("", extra, set(), False, "", "Library")}
    for path, text in configs.items():
        if not fnmatch.fnmatchcase(os.path.basename(path), "*.csproj"):
            continue
        pkgs = _package_refs(text) | extra
        projects[path] = _Project(
            path, pkgs, set(), _test_packages(pkgs), _root_namespace(text),
            _output_type(text))
    return projects


def _package_refs(text):
    names = set()
    if not text:
        return names
    try:
        root = ET.fromstring(text)
    except ET.ParseError:
        return names
    for elem in root.iter():
        if _tag(elem.tag) == "PackageReference":
            name = elem.get("Include") or elem.get("Update")
            if name:
                names.add(name)
    return names


def _root_namespace(text):
    try:
        root = ET.fromstring(text)
    except ET.ParseError:
        return ""
    for elem in root.iter():
        if _tag(elem.tag) == "RootNamespace" and elem.text:
            return elem.text.strip()
    return ""


def _output_type(text):
    try:
        root = ET.fromstring(text)
    except ET.ParseError:
        return "Library"
    for elem in root.iter():
        if _tag(elem.tag) == "OutputType" and elem.text:
            return elem.text.strip()
    return "Library"


def _has_public_top_level(fx):
    if not fx.declares:
        return False
    type_names = {name for _scope, name in fx.declares}
    return bool(type_names & set(fx.exports))


def _supplement_public_types(text, declares, exports, scope, partials):
    """Recover public types when preprocessor blocks break the grammar."""
    existing = {name for _, name, _ in declares}
    for name in PUBLIC_TYPE.findall(text):
        if name not in existing:
            declares.append((scope, name, False))
            partials[(scope, name)] = False
        if name not in exports:
            exports.append(name)


def _test_packages(packages):
    return any(any(t in p.lower() for t in TEST_PACKAGES) for p in packages)


def _parse_error(tree, text):
    err = langkit.first_error(tree)
    if err is None or not _grammar_gap(err, text):
        return err
    return None


def _grammar_gap(err, text):
    if any(m in err for m in ("#if", "#endif", "#else", "#elif", "FEATURE_", "TimeOnly",
                              "DateOnly", "IAsyncDisposable", "AsSpan()", "ReadOnlySpan")):
        return True
    if err.startswith("line 1: unexpected //") and text.lstrip().startswith("//"):
        return "#if" in text
    try:
        line = int(err.split()[1].rstrip(":"))
    except (IndexError, ValueError):
        return False
    lines = text.splitlines()
    if _in_preprocessor_block(lines, line - 1):
        return True
    window = "\n".join(lines[max(0, line - 10):line + 2])
    return "#if" in window or "#endif" in window


def _in_preprocessor_block(lines, idx):
    depth = 0
    for line in lines[: idx + 1]:
        stripped = line.lstrip()
        if stripped.startswith("#if"):
            depth += 1
        elif stripped.startswith("#endif"):
            depth = max(0, depth - 1)
    return depth > 0


def _complexity(root):
    plain = [t for t in COMPLEXITY if isinstance(t, str)]
    n = 1 + langkit.count_types(root, plain)
    for node in langkit.walk(root):
        if node.type != "binary_expression":
            continue
        if node.parent and node.parent.type == "binary_expression":
            continue
        if any(c.type in ("&&", "||", "??") for c in node.children):
            n += 1
    return n


def _namespace_of(node, tree, file_scope):
    parts = []
    cursor = node.parent
    while cursor is not None and cursor != tree.root_node:
        if cursor.type == "namespace_declaration":
            parts.insert(0, _qualified(cursor))
        cursor = cursor.parent
    if parts:
        return ".".join(parts)
    return file_scope


def _file_project(path, projects):
    best, best_len = "", -1
    folder = os.path.dirname(path)
    for proj in projects:
        if not proj:
            continue
        proj_folder = os.path.dirname(proj)
        if folder == proj_folder or folder.startswith(proj_folder + "/"):
            if len(proj_folder) > best_len:
                best, best_len = proj, len(proj_folder)
    return best
