"""C and C++: header/source pairs, #include resolution from build config text."""

import json
import os
import re

import langkit

NAME = "cfamily"
LABEL = "C/C++"
EXTENSIONS = (".c", ".h", ".cc", ".cpp", ".cxx", ".c++", ".hh", ".hpp", ".hxx", ".h++",
              ".ipp", ".tpp", ".inl")
SHEBANGS = ()
GRAMMARS = {ext: "cpp" if ext != ".c" else "c" for ext in EXTENSIONS}
CONFIG = ("CMakeLists.txt", "*.cmake", "Makefile", "*.mk", "meson.build",
          "compile_commands.json")
FIRE = False
SAMPLE = {
    "src/util.h": ("#ifndef UTIL_H\n#define UTIL_H\nvoid util(void);\n#endif\n"),
    "src/util.c": '#include "util.h"\nvoid util(void) {}\n',
    "main.c": '#include "util.h"\n#include <stdio.h>\n\nint main(void) { util(); }\n',
}

HEADER_EXTS = (".h", ".hh", ".hpp", ".hxx", ".h++")
SOURCE_EXTS = (".c", ".cc", ".cpp", ".cxx", ".c++")
TEMPLATE_EXTS = (".ipp", ".tpp", ".inl")
CPP_MARKERS = frozenset({".cc", ".cpp", ".cxx", ".c++", ".hh", ".hpp", ".hxx", ".h++"})
COMMENT = {"comment"}
COMPLEXITY_C = (
    "if_statement", "for_statement", "while_statement", "do_statement", "case_statement",
    "conditional_expression", "preproc_if", "preproc_ifdef", "preproc_elif",
    ("binary_expression", ("&&", "||")),
)
COMPLEXITY_CPP = COMPLEXITY_C + ("for_range_loop", "catch_clause")
FUNCTIONS = ("function_definition",)
ENTRY_NAMES = frozenset({"main", "wmain", "WinMain", "wWinMain"})
INCLUDE_QUOTE = '(preproc_include path: (string_literal) @p)'
INCLUDE_ANGLE = '(preproc_include path: (system_lib_string) @p)'

C_STD = frozenset("""
stdio stdlib string stdint stddef stdbool stdarg limits errno assert math time ctype signal
setjmp locale float inttypes wchar wctype complex fenv iso646 stdalign stdatomic stdnoreturn
threads uchar
""".split())
C_STD_H = frozenset(h + ".h" for h in """
stdio stdlib string stdint stddef stdbool stdarg limits errno assert math time ctype signal
setjmp locale float inttypes wchar wctype complex fenv iso646 stdalign stdatomic stdnoreturn
threads uchar
""".split())
CPP_STD_EXTLESS = frozenset("""
algorithm any array atomic bitset chrono codecvt complex condition_variable deque exception
forward_list fstream functional future initializer_list iomanip ios iosfwd iostream istream
iterator limits list locale map memory mutex new numeric ostream queue random ratio regex
scoped_allocator set shared_mutex sstream stack stdexcept streambuf string string_view
strstream system_error thread tuple typeindex typeinfo type_traits unordered_map
unordered_set utility valarray vector version
""".split())
POSIX = frozenset("""
unistd fcntl pthread dlfcn dirent poll netdb termios windows winsock2 ws2tcpip
""".split())
POSIX_H = frozenset(h + ".h" for h in POSIX)
GENERATED = re.compile(r"\b(?:generated by|DO NOT EDIT)\b", re.I)
CMAKE_INC = re.compile(
    r"(?:target_)?include_directories\s*\(\s*(?:SYSTEM\s+)?(?:(?:PUBLIC|PRIVATE|INTERFACE)\s+)*(.+?)\s*\)",
    re.I | re.S)
MESON_INC = re.compile(r"include_directories\s*\(\s*(.+?)\s*\)", re.S)
MESON_STR = re.compile(r"'([^']+)'|\"([^\"]+)\"")
MAKE_I = re.compile(r"(?:^|[\s\"'])-I(?!\w)([^\s\"']+)|(?:^|[\s\"'])-I\s+([^\s\"']+)")
CMAKE_VARS = {
    "${CMAKE_CURRENT_SOURCE_DIR}", "${CMAKE_CURRENT_LIST_DIR}",
    "${PROJECT_SOURCE_DIR}", "${CMAKE_SOURCE_DIR}",
}


def _ext(path):
    return os.path.splitext(path)[1]


def _is_header(path):
    return _ext(path) in HEADER_EXTS


def _is_source(path):
    return _ext(path) in SOURCE_EXTS


def _is_template(path):
    return _ext(path) in TEMPLATE_EXTS


def _stem(path):
    return os.path.splitext(path)[0]


def _base_stem(path):
    return os.path.splitext(os.path.basename(path))[0]


def _dir(path):
    d = os.path.dirname(path)
    return d if d else ""


def _join(base, rel):
    if not base or base == "./":
        return rel
    if not rel:
        return base
    return base + "/" + rel


def _cpp_repo(files):
    return any(_ext(f) in CPP_MARKERS for f in files)


def grammar_for(path, files):
    if _ext(path) == ".h":
        return "cpp" if _cpp_repo(files) else "c"
    return GRAMMARS.get(_ext(path), "cpp")


def _header_exts_for(stem, folder, files):
    found = []
    for ext in HEADER_EXTS:
        candidate = _join(folder, stem + ext) if folder else stem + ext
        if candidate in files:
            found.append(candidate)
    return found


def _mirror_candidates(src, files):
    parts = src.split("/")
    if "src" not in parts:
        return []
    idx = parts.index("src")
    rel = "/".join(parts[idx + 1:])
    rel_stem = _stem(rel)
    rel_base = _base_stem(rel)
    found = []
    for h in files:
        if not _is_header(h):
            continue
        hparts = h.split("/")
        if "include" not in hparts:
            continue
        hidx = hparts.index("include")
        hrel = "/".join(hparts[hidx + 1:])
        h_stem = _stem(hrel)
        h_base = _base_stem(hrel)
        h_parts = h_stem.split("/")
        h_drop = "/".join(h_parts[1:]) if len(h_parts) > 1 else h_base
        if rel_stem in (h_stem, h_drop) or rel_base in (h_base, h_drop):
            found.append(h)
    return found


def _pair_header(path, files):
    folder = _dir(path)
    stem = _base_stem(path)
    local = _header_exts_for(stem, folder, files)
    mirror = _mirror_candidates(path, files)
    candidates = sorted(set(local + mirror))
    return candidates[0] if len(candidates) == 1 else None


def unit_of(path, files):
    if _is_header(path):
        return path
    if _is_source(path) or _is_template(path):
        paired = _pair_header(path, files)
        return paired if paired else path
    return path


def is_test(path, text=None):
    parts = path.split("/")
    name = parts[-1]
    if any(p in ("test", "tests", "unittest", "unittests", "testing") for p in parts[:-1]):
        return True
    base, ext = os.path.splitext(name)
    return (base.endswith("_test") or base.endswith("_unittest") or base.endswith("_tests")
            or name.startswith("test_") or base.endswith("Test"))


def is_excluded(path, text):
    parts = path.split("/")
    if any(p == "build" or p.startswith("cmake-build-") or p == "out" for p in parts[:-1]):
        return True
    name = parts[-1]
    if name.endswith(".pb.h") or name.endswith(".pb.cc") or name.endswith(".generated.h"):
        return True
    if name.endswith("_generated.h"):
        return True
    if text and GENERATED.search(_first_comment(text)):
        return True
    return False


def _first_comment(text):
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("//"):
            return stripped[2:].strip()
        if stripped.startswith("/*"):
            return stripped[2:].strip(" *")
    return ""


def _include_guards(tree):
    guards = set()
    if tree is None:
        return guards
    for node in langkit.walk(tree.root_node):
        if node.type != "preproc_ifdef":
            continue
        children = [c for c in node.children if c.type in ("identifier", "preproc_def", "#ifndef")]
        if not children or children[0].type != "#ifndef":
            continue
        ifndef_name = None
        for c in node.children:
            if c.type == "identifier":
                ifndef_name = langkit.node_text(c)
                break
        for c in node.children:
            if c.type != "preproc_def":
                continue
            ids = [x for x in c.children if x.type == "identifier"]
            vals = [x for x in c.children if x.type in ("preproc_arg", "preproc_params")]
            if ids and not vals and ifndef_name and langkit.node_text(ids[0]) == ifndef_name:
                guards.add(ifndef_name)
    return guards


def _decl_name(node):
    for n in langkit.walk(node):
        if n.type == "identifier":
            return langkit.node_text(n)
        if n.type == "type_identifier":
            return langkit.node_text(n)
    return None


def _function_decl_name(node):
    for n in langkit.walk(node):
        if n.type == "function_declarator":
            for c in n.children:
                if c.type == "identifier":
                    return langkit.node_text(c)
    return None


def _is_static(node):
    return any(c.type == "storage_class_specifier" and langkit.node_text(c) == "static"
               for c in node.children)


def _export_from_node(node):
    if node.type == "declaration":
        return _function_decl_name(node) or _decl_name(node)
    if node.type in ("struct_specifier", "union_specifier", "enum_specifier", "class_specifier",
                     "type_definition", "alias_declaration"):
        return _decl_name(node)
    return None


def _collect_header_exports(root, guards):
    names = set()
    containers = ("translation_unit", "namespace_definition", "preproc_ifdef", "preproc_if",
                  "preproc_elif", "linkage_specification")

    def walk(node):
        for child in node.children:
            if child.type in ("preproc_def", "preproc_function_def"):
                ids = [c for c in child.children if c.type == "identifier"]
                if ids:
                    name = langkit.node_text(ids[0])
                    if name not in guards:
                        names.add(name)
            elif child.type in containers:
                walk(child)
            elif child.type == "function_definition":
                continue
            else:
                n = _export_from_node(child)
                if n:
                    names.add(n)

    walk(root)
    return tuple(sorted(names))


def _collect_source_exports(root):
    names = set()
    stack = [root]
    while stack:
        node = stack.pop()
        if node.type not in ("translation_unit", "namespace_definition"):
            continue
        for child in node.children:
            if child.type == "namespace_definition":
                stack.append(child)
            elif child.type == "function_definition" and not _is_static(child):
                n = _function_decl_name(child)
                if n:
                    names.add(n)
    return tuple(sorted(names))


def _imports(root, grammar):
    imports = []
    for node in langkit.captures(grammar, INCLUDE_QUOTE, root).get("p", []):
        spec = langkit.node_text(node).strip('"')
        imports.append(langkit.Import(spec, ("quote",)))
    for node in langkit.captures(grammar, INCLUDE_ANGLE, root).get("p", []):
        spec = langkit.node_text(node).strip("<>")
        imports.append(langkit.Import(spec, ("angle",)))
    return tuple(imports)


def _tree_grammar(path, tree):
    if _ext(path) == ".c":
        return "c"
    if _ext(path) != ".h":
        return "cpp"
    if tree is None:
        return "c"
    root = tree.root_node
    c_count = len(langkit.captures("c", INCLUDE_QUOTE, root).get("p", []))
    c_count += len(langkit.captures("c", INCLUDE_ANGLE, root).get("p", []))
    cpp_count = len(langkit.captures("cpp", INCLUDE_QUOTE, root).get("p", []))
    cpp_count += len(langkit.captures("cpp", INCLUDE_ANGLE, root).get("p", []))
    return "c" if c_count >= cpp_count else "cpp"


def scan(path, text, tree):
    if tree is None:
        return langkit.Facts()
    grammar = _tree_grammar(path, tree)
    root = tree.root_node
    guards = _include_guards(tree)
    if _is_header(path):
        exports = _collect_header_exports(root, guards)
    elif _is_source(path):
        exports = _collect_source_exports(root)
    else:
        exports = ()
    complexity_types = COMPLEXITY_CPP if grammar == "cpp" else COMPLEXITY_C
    entry = any(langkit.node_text(n) in ENTRY_NAMES
                for n in langkit.captures(grammar,
                                          '(function_definition declarator: '
                                          '(function_declarator declarator: (identifier) @n))',
                                          root).get("n", []))
    return langkit.Facts(
        loc=langkit.loc(text, tree, COMMENT),
        complexity=1 + langkit.count_types(root, complexity_types),
        exports=exports,
        notes=langkit.notes(tree, COMMENT),
        is_entry=entry,
        parse_error=langkit.first_error(tree),
        imports=_imports(root, grammar),
        functions=langkit.functions(root, FUNCTIONS,
                                    lambda n: 1 + langkit.count_types(n, complexity_types)),
    )


def _repo_root(files):
    if not files:
        return ""
    parts = files[0].split("/")
    return ""


def _folder_exists(folder, files):
    if folder in ("", "./"):
        return bool(files)
    prefix = folder.rstrip("/") + "/"
    return any(f.startswith(prefix) or f == folder for f in files)


def _cmake_paths(text, cmakedir, root):
    paths = []
    for match in CMAKE_INC.finditer(text or ""):
        body = match.group(1)
        for token in re.split(r"[\s\n]+", body.strip()):
            token = token.strip(")")
            if not token or token.startswith("$<") or "${" in token and not any(
                    v in token for v in CMAKE_VARS):
                continue
            token = token.replace("${CMAKE_CURRENT_SOURCE_DIR}", cmakedir)
            token = token.replace("${CMAKE_CURRENT_LIST_DIR}", cmakedir)
            token = token.replace("${PROJECT_SOURCE_DIR}", root)
            token = token.replace("${CMAKE_SOURCE_DIR}", root)
            if "${" in token:
                continue
            rel = token.lstrip("/")
            paths.append(_join(cmakedir, rel) if not os.path.isabs(token) else token.lstrip("/"))
    return paths


def _meson_paths(text, cfgdir):
    paths = []
    for match in MESON_INC.finditer(text or ""):
        for sm in MESON_STR.finditer(match.group(1)):
            rel = sm.group(1) or sm.group(2)
            paths.append(_join(cfgdir, rel))
    return paths


def _make_paths(text, cfgdir):
    paths = []
    for match in MAKE_I.finditer(text or ""):
        raw = match.group(1) or match.group(2)
        if raw:
            paths.append(_join(cfgdir, raw) if not raw.startswith("/") else raw.lstrip("/"))
    return paths


def _compile_commands_paths(text):
    paths = []
    try:
        entries = json.loads(text or "[]")
    except json.JSONDecodeError:
        return paths
    if isinstance(entries, dict):
        entries = [entries]
    for entry in entries:
        args = entry.get("arguments") or entry.get("command", "").split()
        cfgdir = _dir(entry.get("file", ""))
        for i, arg in enumerate(args):
            if arg == "-I" and i + 1 < len(args):
                paths.append(_join(cfgdir, args[i + 1]))
            elif arg.startswith("-I") and len(arg) > 2:
                paths.append(_join(cfgdir, arg[2:]))
    return paths


def _tracked_include_folders(files):
    found = set()
    for f in files:
        parts = f.split("/")
        for i, part in enumerate(parts[:-1]):
            if part == "include":
                found.add("/".join(parts[: i + 1]))
    return sorted(found)


def _build_include_dirs(configs, files):
    root = _repo_root(files)
    ordered = []
    seen = set()
    for cfg_path in sorted(configs):
        text = configs[cfg_path]
        cfgdir = _dir(cfg_path)
        base = os.path.basename(cfg_path)
        if base == "compile_commands.json":
            extra = _compile_commands_paths(text)
        elif base == "meson.build":
            extra = _meson_paths(text, cfgdir)
        elif base == "Makefile" or base.endswith(".mk"):
            extra = _make_paths(text, cfgdir)
        else:
            extra = _cmake_paths(text, cfgdir, root)
        for path in extra:
            norm = path.rstrip("/") or "./"
            if norm not in seen:
                seen.add(norm)
                ordered.append(norm)
    for folder in _tracked_include_folders(files):
        if folder not in seen:
            seen.add(folder)
            ordered.append(folder)
    for special in ("src", "./"):
        if _folder_exists(special if special != "./" else "", files):
            norm = special
            if norm not in seen:
                seen.add(norm)
                ordered.append(norm)
    return ordered


def _is_system_header(spec):
    base = spec.split("/")[-1]
    stem, ext = os.path.splitext(base)
    if ext == ".h" and (stem in C_STD or base in C_STD_H):
        return True
    if stem.startswith("c") and len(stem) > 1 and stem[1:] in C_STD:
        return True
    if "/" not in spec and "." not in spec and spec in CPP_STD_EXTLESS:
        return True
    if base in POSIX_H or stem in POSIX:
        return True
    if spec.startswith(("sys/", "netinet/", "arpa/", "mach/", "CoreFoundation/")):
        return True
    return False


def _warehouse(spec):
    if "/" in spec:
        return spec.split("/")[0]
    stem, ext = os.path.splitext(spec)
    return stem if ext else spec


def _tracked_folder(name, files):
    prefix = name + "/"
    return any(f.startswith(prefix) for f in files)


def _suffix_matches(spec, files):
    needle = "/" + spec
    return sorted(f for f in files if f.endswith(needle))


def _unique_suffix(spec, files):
    """Exactly one tracked path ends with /<spec>, or nothing."""
    matches = _suffix_matches(spec, files)
    return matches[0] if len(matches) == 1 else None


def _fallback_tracked(spec, files):
    """After include-dir lookup fails: root path, unique suffix, then drop a
    leading segment when that name is not a tracked folder but the rest is a
    root header (e.g. <hiredis/hiredis.h> -> hiredis.h)."""
    if spec in files:
        return spec
    found = _unique_suffix(spec, files)
    if found:
        return found
    if "/" not in spec:
        return None
    first, rest = spec.split("/", 1)
    if _tracked_folder(first, files):
        return None
    if rest in files:
        return rest
    return None


class Resolver:
    def __init__(self, include_dirs, files):
        self._dirs = include_dirs
        self._files = frozenset(files)

    def resolve(self, path, imp):
        spec = imp.spec
        quoted = imp.names and imp.names[0] == "quote"
        search = []
        if quoted:
            search.append(_dir(path))
        search.extend(self._dirs)
        for folder in search:
            candidate = _join(folder, spec)
            if candidate in self._files:
                return frozenset([candidate]), None
        found = _fallback_tracked(spec, self._files)
        if found:
            return frozenset([found]), None
        if len(_suffix_matches(spec, self._files)) > 1:
            return frozenset(), None
        if quoted:
            return frozenset(), None
        if _is_system_header(spec):
            return frozenset(), None
        return frozenset(), _warehouse(spec)


def resolver(facts, configs, files):
    return Resolver(_build_include_dirs(configs, files), files)
