"""Java and Kotlin: one building per file, imports resolved through a shared symbol index."""

import langkit

NAME = "jvm"
LABEL = "Java/Kotlin"
EXTENSIONS = (".java", ".kt", ".kts")
SHEBANGS = ("kotlin", "kotlinc")
GRAMMARS = {".java": "java", ".kt": "kotlin", ".kts": "kotlin"}
CONFIG = ()
FIRE = (".java", ".kt", ".kts")
SAMPLE = {
    "src/main/java/com/a/App.java": (
        "package com.a;\n\nimport com.b.Util;\n\npublic class App {\n"
        "    public static void main(String[] args) { Util.run(); }\n}\n"
    ),
    "lib/com/b/Util.java": "package com.b;\n\npublic class Util { public static void run() {} }\n",
    "src/test/java/com/a/AppTest.java": (
        "package com.a;\n\npublic class AppTest {\n"
        "    @org.junit.jupiter.api.Test void t() { new App(); }\n}\n"
    ),
}

JAVA_COMMENT = {"line_comment", "block_comment"}
KOTLIN_COMMENT = {"line_comment", "multiline_comment"}
JAVA_COMPLEXITY = (
    "if_statement", "for_statement", "enhanced_for_statement", "while_statement",
    "do_statement", "switch_label", "catch_clause", "ternary_expression",
    ("binary_expression", ("&&", "||")),
)
KOTLIN_COMPLEXITY = (
    "if_expression", "for_statement", "while_statement", "do_while_statement",
    "when_entry", "catch_block", "conjunction_expression", "disjunction_expression",
    "elvis_expression",
)
JAVA_FUNCTIONS = ("method_declaration", "constructor_declaration",
                  "compact_constructor_declaration")
KOTLIN_FUNCTIONS = ("function_declaration", "secondary_constructor")
JAVA_DECLARE = (
    "class_declaration", "interface_declaration", "enum_declaration",
    "record_declaration", "annotation_type_declaration",
)
STD_PREFIXES = ("java.", "javax.", "jdk.", "sun.", "kotlin.", "org.w3c.")
TEST_DIRS = ("src/test/", "src/androidTest/", "src/testFixtures/", "src/integrationTest/")
EXCLUDE_DIRS = ("build/", "generated/", "generated-sources/")


def _ext(path):
    for ext in (".java", ".kts", ".kt"):
        if path.endswith(ext):
            return ext
    return ""


def _grammar(path):
    return GRAMMARS[_ext(path)]


def unit_of(path, files):
    return path


def is_test(path, text=None):
    if any(d in path for d in TEST_DIRS):
        return True
    base = path.rsplit("/", 1)[-1]
    stem = base.rsplit(".", 1)[0]
    return stem.endswith(("Test", "Tests", "IT", "Spec"))


def is_excluded(path, text):
    if any(f"/{d}" in f"/{path}/" for d in EXCLUDE_DIRS):
        return True
    head = text[:4096]
    for marker in ("@generated", "Generated by"):
        if marker in head:
            return True
    return False


def _has_modifier(node, grammar, *names):
    mods = langkit.captures(grammar, f"({node.type} (modifiers) @m)", node).get("m", [])
    if not mods:
        return False
    text = langkit.node_text(mods[0])
    return any(f"{n} " in text or text.endswith(n) or f" {n}" in text for n in names)


def _java_scope(root):
    nodes = langkit.captures("java", "(package_declaration (scoped_identifier) @p)", root).get("p", [])
    return langkit.node_text(nodes[0]) if nodes else ""


def _kotlin_scope(root):
    nodes = langkit.captures("kotlin", "(package_header) @p", root).get("p", [])
    if not nodes:
        return ""
    text = langkit.node_text(nodes[0])
    return text[8:].strip() if text.startswith("package ") else text.strip()


def _java_declares(root):
    names = []
    for kind in JAVA_DECLARE:
        for node in langkit.captures("java", f"({kind} name: (identifier) @n)", root).get("n", []):
            names.append(langkit.node_text(node))
    return tuple(sorted(set(names)))


def _kotlin_top_level(root):
    for child in root.children:
        if child.type in ("class_declaration", "type_alias", "function_declaration",
                          "property_declaration"):
            yield child
        elif child.type == "infix_expression" and child.children and child.children[0].type == "object_literal":
            yield child


def _kotlin_object_name(node):
    for child in node.children:
        if child.type == "simple_identifier":
            return langkit.node_text(child)
    return None


def _kotlin_name(node):
    if node.type == "class_declaration":
        for c in node.children:
            if c.type == "type_identifier":
                return langkit.node_text(c)
    elif node.type == "type_alias":
        for c in node.children:
            if c.type == "type_identifier":
                return langkit.node_text(c)
    elif node.type == "function_declaration":
        for c in node.children:
            if c.type == "simple_identifier":
                return langkit.node_text(c)
    elif node.type == "property_declaration":
        for c in node.children:
            if c.type == "variable_declaration":
                for cc in c.children:
                    if cc.type == "simple_identifier":
                        return langkit.node_text(cc)
    return None


def _kotlin_declares(root):
    names = []
    for node in _kotlin_top_level(root):
        if node.type == "infix_expression":
            name = _kotlin_object_name(node)
            if name:
                names.append(name)
            continue
        name = _kotlin_name(node)
        if name:
            names.append(name)
    return tuple(sorted(set(names)))


def _java_exports(root):
    names = []
    for kind in JAVA_DECLARE:
        for decl in langkit.captures("java", f"({kind}) @d", root).get("d", []):
            if not _has_modifier(decl, "java", "public"):
                continue
            type_name = langkit.captures("java", f"({kind} name: (identifier) @n)", decl).get("n", [])
            if not type_name:
                continue
            names.append(langkit.node_text(type_name[0]))
            for md in langkit.captures("java", "(method_declaration) @m", decl).get("m", []):
                if _has_modifier(md, "java", "public"):
                    mn = langkit.captures("java", "(method_declaration name: (identifier) @n)", md)
                    if mn.get("n"):
                        names.append(langkit.node_text(mn["n"][0]))
            for fd in langkit.captures("java", "(field_declaration) @f", decl).get("f", []):
                if _has_modifier(fd, "java", "public"):
                    for vn in langkit.captures("java",
                                               "(variable_declarator name: (identifier) @n)",
                                               fd).get("n", []):
                        names.append(langkit.node_text(vn))
    return tuple(sorted(set(names)))


def _kotlin_hidden(node):
    return _has_modifier(node, "kotlin", "private", "internal")


def _kotlin_exports(root):
    names = []
    for node in _kotlin_top_level(root):
        if _kotlin_hidden(node):
            continue
        if node.type == "infix_expression":
            name = _kotlin_object_name(node)
            if name:
                names.append(name)
            body = next((c for c in node.children if c.type == "lambda_literal"), None)
            if body:
                for n in langkit.walk(body):
                    if n.type == "function_declaration" and not _kotlin_hidden(n):
                        fn = langkit.captures("kotlin",
                                              "(function_declaration (simple_identifier) @n)",
                                              n).get("n", [])
                        if fn:
                            names.append(langkit.node_text(fn[0]))
            continue
        if node.type == "class_declaration":
            tn = langkit.captures("kotlin", "(class_declaration (type_identifier) @n)", node)
            if tn.get("n"):
                names.append(langkit.node_text(tn["n"][0]))
            for n in langkit.walk(node):
                if n.type in ("function_declaration", "property_declaration") and n.parent.type == "class_body":
                    if not _kotlin_hidden(n):
                        if n.type == "function_declaration":
                            fn = langkit.captures("kotlin",
                                                  "(function_declaration (simple_identifier) @n)",
                                                  n).get("n", [])
                            if fn:
                                names.append(langkit.node_text(fn[0]))
                        else:
                            for vn in langkit.captures("kotlin",
                                                       "(property_declaration (variable_declaration "
                                                       "(simple_identifier) @n))", n).get("n", []):
                                names.append(langkit.node_text(vn))
            continue
        if node.type == "type_alias":
            tn = langkit.captures("kotlin", "(type_alias (type_identifier) @n)", node).get("n", [])
            if tn:
                names.append(langkit.node_text(tn[0]))
            continue
        if node.type == "function_declaration":
            fn = langkit.captures("kotlin", "(function_declaration (simple_identifier) @n)", node)
            if fn.get("n"):
                names.append(langkit.node_text(fn["n"][0]))
            continue
        if node.type == "property_declaration":
            for vn in langkit.captures("kotlin",
                                       "(property_declaration (variable_declaration "
                                       "(simple_identifier) @n))", node).get("n", []):
                names.append(langkit.node_text(vn))
    return tuple(sorted(set(names)))


def _java_references(root, declared):
    refs = set()
    for n in langkit.walk(root):
        if n.type == "type_identifier":
            name = langkit.node_text(n)
            if name and name not in declared:
                refs.add(name)
        elif n.type == "method_invocation":
            obj = langkit.captures("java", "(method_invocation object: (_) @o)", n).get("o", [])
            if obj and obj[0].type == "identifier":
                name = langkit.node_text(obj[0])
                if name and name not in declared:
                    refs.add(name)
        elif n.type == "field_access":
            obj = langkit.captures("java", "(field_access object: (_) @o)", n).get("o", [])
            if obj and obj[0].type == "identifier":
                name = langkit.node_text(obj[0])
                if name and name not in declared:
                    refs.add(name)
    return tuple(sorted(refs))


def _kotlin_references(root, declared):
    refs = set()
    for n in langkit.walk(root):
        if n.type == "user_type":
            for c in n.children:
                if c.type == "type_identifier":
                    name = langkit.node_text(c)
                    if name and name not in declared:
                        refs.add(name)
        elif n.type == "call_expression":
            callee = n.children[0] if n.children else None
            if callee is not None:
                if callee.type == "simple_identifier":
                    name = langkit.node_text(callee)
                    if name and name not in declared:
                        refs.add(name)
                elif callee.type == "navigation_expression":
                    recv = langkit.captures("kotlin",
                                            "(navigation_expression (simple_identifier) @r)",
                                            callee).get("r", [])
                    if recv:
                        name = langkit.node_text(recv[0])
                        if name and name not in declared:
                            refs.add(name)
        elif n.type == "navigation_expression" and n.parent.type != "call_expression":
            recv = langkit.captures("kotlin", "(navigation_expression (simple_identifier) @r)", n)
            if recv.get("r"):
                name = langkit.node_text(recv["r"][0])
                if name and name not in declared:
                    refs.add(name)
    return tuple(sorted(refs))


def _java_imports(root):
    imports = []
    for node in langkit.captures("java", "(import_declaration) @i", root).get("i", []):
        text = langkit.node_text(node)
        scoped = None
        for n in node.children:
            if n.type == "scoped_identifier":
                scoped = langkit.node_text(n)
                break
        if scoped is None:
            continue
        if text.strip().endswith("*;"):
            pkg = scoped
            imports.append(langkit.Import(f"{pkg}.*"))
        elif " static " in f" {text} ":
            parts = scoped.rsplit(".", 1)
            imports.append(langkit.Import(parts[0] if len(parts) == 2 else scoped))
        else:
            imports.append(langkit.Import(scoped))
    return imports


def _kotlin_imports(root):
    imports = []
    for node in langkit.captures("kotlin", "(import_header) @i", root).get("i", []):
        ident = None
        wild = False
        for n in node.children:
            if n.type == "identifier":
                ident = langkit.node_text(n)
            elif n.type == "wildcard_import":
                wild = True
        if ident is None:
            continue
        imports.append(langkit.Import(f"{ident}.*" if wild else ident))
    return imports


def _reference_imports(refs):
    return [langkit.Import(name, kind="reference") for name in refs]


def _java_main(root):
    for method in langkit.captures("java", "(method_declaration) @m", root).get("m", []):
        names = langkit.captures("java", "(method_declaration name: (identifier) @n)", method)
        if not names.get("n") or langkit.node_text(names["n"][0]) != "main":
            continue
        if not _has_modifier(method, "java", "public") or not _has_modifier(method, "java", "static"):
            continue
        text = langkit.node_text(method)
        if "void main" not in text:
            continue
        if "String[]" in text or "String ..." in text or "String..." in text:
            return True
    return False


def _kotlin_main(root, path):
    if path.endswith(".kts"):
        return True
    for node in _kotlin_top_level(root):
        if node.type != "function_declaration":
            continue
        fn = langkit.captures("kotlin", "(function_declaration (simple_identifier) @n)", node)
        if fn.get("n") and langkit.node_text(fn["n"][0]) == "main":
            return True
    return False


def scan(path, text, tree):
    if tree is None:
        return langkit.Facts()
    grammar = _grammar(path)
    root = tree.root_node
    comments = JAVA_COMMENT if grammar == "java" else KOTLIN_COMMENT
    if grammar == "java":
        scope = _java_scope(root)
        declares = _java_declares(root)
        refs = _java_references(root, set(declares))
        imports = _java_imports(root)
        exports = _java_exports(root)
        complexity = 1 + langkit.count_types(root, JAVA_COMPLEXITY)
        functions = langkit.functions(root, JAVA_FUNCTIONS,
                                      lambda n: 1 + langkit.count_types(n, JAVA_COMPLEXITY))
        entry = _java_main(root)
    else:
        scope = _kotlin_scope(root)
        declares = _kotlin_declares(root)
        refs = _kotlin_references(root, set(declares))
        imports = _kotlin_imports(root)
        exports = _kotlin_exports(root)
        complexity = 1 + langkit.count_types(root, KOTLIN_COMPLEXITY)
        functions = langkit.functions(
            root, KOTLIN_FUNCTIONS, lambda n: 1 + langkit.count_types(n, KOTLIN_COMPLEXITY),
            lambda n: "constructor" if n.type == "secondary_constructor" else None)
        entry = _kotlin_main(root, path)
    imports = tuple(imports + _reference_imports(refs))
    return langkit.Facts(
        loc=langkit.loc(text, tree, comments),
        complexity=complexity,
        exports=exports,
        notes=langkit.notes(tree, comments),
        is_entry=entry,
        parse_error=langkit.first_error(tree),
        imports=imports,
        scope=scope,
        declares=declares,
        references=refs,
        functions=functions,
    )


def _is_stdlib(spec):
    if spec.startswith("kotlinx."):
        return False
    return any(spec.startswith(p) for p in STD_PREFIXES)


def _warehouse(spec):
    if spec.startswith("androidx."):
        return "androidx"
    if spec.startswith("android."):
        return "android"
    parts = spec.split(".")
    if len(parts) >= 2:
        return ".".join(parts[:2])
    return parts[0] if parts else spec


def _resolve_spec(index, spec):
    if spec.endswith(".*"):
        return None
    parts = spec.split(".")
    if len(parts) < 2:
        return index.lookup("", parts[0]) if len(parts) == 1 else None
    for i in range(len(parts) - 1, 0, -1):
        scope = ".".join(parts[:i])
        name = parts[i]
        hit = index.lookup(scope, name)
        if hit:
            return hit
    return None


class Resolver:
    def __init__(self, facts, index):
        self._facts = facts
        self._index = index

    def resolve(self, path, imp):
        if imp.kind == "reference":
            scope = self._facts[path].scope or ""
            hit = self._index.lookup(scope, imp.spec)
            if hit and hit != path:
                return frozenset([hit]), None
            return frozenset(), None
        spec = imp.spec
        if spec.endswith(".*"):
            pkg = spec[:-2]
            refs = self._facts[path].references
            hits = {self._index.lookup(pkg, r) for r in refs}
            hits.discard(None)
            return frozenset(hits), None
        hit = _resolve_spec(self._index, spec)
        if hit:
            return frozenset([hit]), None
        if _is_stdlib(spec):
            return frozenset(), None
        return frozenset(), _warehouse(spec)


def resolver(facts, configs, files):
    decls = []
    for path, fx in facts.items():
        scope = fx.scope or ""
        for name in fx.declares:
            decls.append((scope, name, path))
    return Resolver(facts, langkit.SymbolIndex(decls))
